# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.IntegerField(choices=[(1, 'Character'), (2, 'Text'), (3, 'Email'), (4, 'Boolean'), (5, 'Date Time'), (6, 'File'), (7, 'Image'), (8, 'Decimal'), (9, 'Float'), (10, 'Time'), (11, 'Url'), (12, 'Enum')], default=1)),
                ('field_name', models.CharField(max_length=100)),
                ('char_field', models.CharField(blank=True, max_length=100, null=True)),
                ('text_field', models.TextField(blank=True, null=True)),
                ('email_field', models.EmailField(blank=True, max_length=250, null=True)),
                ('boolean_field', models.BooleanField()),
                ('date_time_field', models.DateTimeField(blank=True, null=True)),
                ('file_field', models.FileField(blank=True, upload_to=None)),
                ('image_field', models.ImageField(blank=True, upload_to=None)),
                ('decimal_field', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('float_field', models.FloatField(blank=True, null=True)),
                ('time_field', models.TimeField(blank=True, null=True)),
                ('url_field', models.URLField(blank=True)),
                ('choices_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk.ChoicesField')),
            ],
            options={
                'ordering': ('field_name',),
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RisksFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Fields')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Risk')),
            ],
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='fields',
            field=models.ManyToManyField(through='risk.RisksFields', to='risk.Fields'),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.RiskType'),
        ),
    ]
