# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='field_types',
            new_name='fields',
        ),
        migrations.AlterField(
            model_name='risk',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
