# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_auto_20180207_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicesfield',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
