# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_auto_20180212_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='slug',
        ),
        migrations.AlterField(
            model_name='risk',
            name='fields',
            field=models.ManyToManyField(to='risk.FieldType'),
        ),
    ]
